### ISSUE TITLE
Pypi does not recognize license

### ISSUE THREAD

**Issue by SMoraisAnsys** [python-attrs/attrs#1386]
Unless there is a delay, it seems that the LICENSE metadata is not available in Pypi for release 24.3.0, see https://pypi.org/project/attrs/24.3.0/

Note that this information was available in 24.2.0, see https://pypi.org/project/attrs/24.2.0/

I suspect the changes from https://github.com/python-attrs/attrs/pull/1377 are the cause for this problem.

**Comment by hugovk** [comment]
Testing with another package that also uses Hatchling, this is how [pyproject.toml](https://github.com/hugovk/tinytext/blob/1a161c3b612361b2c58dc735d3dfda84ccb849e9/pyproject.toml) was before:

```toml
license = { text = "MIT" }
classifiers = [
  "License :: OSI Approved :: MIT License",
```

The upload shows it had this [metadata](https://github.com/hugovk/tinytext/actions/runs/12349074467):

```
Metadata-Version: 2.4
License: MIT
License-File: LICENSE.txt
Classifier: License :: OSI Approved :: MIT License
```

[PyPI](https://test.pypi.org/project/tinytext/3.10.1.dev11/) shows:

Unverified details:
* Meta:
  * License: MIT License (MIT)


---

Next, [change](https://github.com/hugovk/tinytext/commit/707bec439882dbc3d67be7d05d7864c28478a25f#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R19) to:

```toml
license = "MIT"
license-files = [ "LICENSE.txt" ]
classifiers = [
  "License :: OSI Approved :: MIT License",
```

[Metadata](https://github.com/hugovk/tinytext/actions/runs/12349309612):

```
Metadata-Version: 2.4
Name: tinytext
License-Expression: MIT
License-File: LICENSE.txt
Classifier: License :: OSI Approved :: MIT License
```

[PyPI](https://test.pypi.org/project/tinytext/3.10.1.dev12/):

Unverified details:
* Meta:
  * License: MIT License


(It changed from "MIT License (MIT)" to "MIT License".)

---

Finally, [remove](https://github.com/hugovk/tinytext/commit/d16cada1b58eee89b7f03589e3a3507a4dc4d6f2) the Trove classifier:

```toml
license = "MIT"
license-files = [ "LICENSE.txt" ]
```

[Metadata](https://github.com/hugovk/tinytext/actions/runs/12349917412):

```
Metadata-Version: 2.4
Name: tinytext
License-Expression: MIT
License-File: LICENSE.txt
```

[PyPI](https://test.pypi.org/project/tinytext/3.10.1.dev13/):

Unverified details:
* Meta:
  * [no licence shown]

---

To summarise, the new `License-Expression` and `License-File` fields are being added to metadata, but the licence is only shown (as unverified) when using the Trove classifier.

This might be a PyPI bug? Looking at https://pypi.org/pypi/attrs/json I see:

```json
"license": null,
"license_expression": null,
"license_files": null,
```

So I think the short-term fix for attrs is to keep the Trove classifier (it's only deprecated for now, not removed), and keep the new PEP 639 fields so they can be used when PyPI is ready:

```toml
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
  "License :: OSI Approved :: MIT License",
```

**Comment by hugovk** [comment]
> This might be a PyPI bug?

Or rather twine? Quoting @konstin on the PyPA Discord talking about another issue but with timely relevant info:

> ... uv publish sets license-file in the formdata (https://github.com/astral-sh/uv/blob/8074917449ec53d238112a9b0722110d902f522e/crates/uv-publish/src/lib.rs#L699) while twine does not (yet) (https://github.com/pypa/twine/blob/75be078d2849d07c3406772cbbdb13c72139b341/twine/package.py#L199)

**Comment by konstin** [comment]
The warehouse (pypi) side is working, the following test package shows up correctly (https://test.pypi.org/project/astral-test-token/):

![image](https://github.com/user-attachments/assets/27224a89-513c-467f-929a-42b55b81f1ff)

```toml
[project]
name = "astral-test-token"
version = "0.1.2317"
authors = [{ name = "konstin", email = "konstin@mailbox.org" }]
classifiers = ["Topic :: Software Development :: Testing"]
# Empty for simplicity with the `uv compile` check, anyio still tests,
# optional-dependencies still test the `Requires-Dist` field.
dependencies = []
description = "Add your description here"
dynamic = ["gui-scripts", "scripts"]
keywords = ["test", "publish"]
license = "MIT OR Apache-2.0"
license-files = ["LICENSE*"]
maintainers = [{ name = "konstin", email = "konstin@mailbox.org" }]
optional-dependencies = { "async" = ["anyio>=4,<5"] }
readme = "README.md"
requires-python = ">=3.12"
urls = { "github" = "https://github.com/astral-sh/uv" }

# hatchling should work equally
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
